"""Yerel, sürümlenmiş CSV dosyalarından tarayıcı verisini yeniden üretir.
Çalıştırma: python veriler/hazirla.py (proje kökünden). Ağ erişimi gerekmez.
"""
from pathlib import Path
import csv
import json

ROOT = Path(__file__).resolve().parents[1]
definitions = [
    ('school','Okul','category','GP veya MS; iki Portekiz okulu'),
    ('sex','Kaynak veride cinsiyet','category','F: kadın, M: erkek; kaynak dosyanın kodlaması'),
    ('age','Yaş','numeric','Yıl; gözlenen aralık 15–22'),
    ('address','Yerleşim','category','U: kentsel, R: kırsal'),
    ('famsize','Hane büyüklüğü','category','LE3: en çok 3, GT3: 3 kişiden fazla'),
    ('Pstatus','Ebeveynlerin birlikte yaşaması','category','T: birlikte, A: ayrı'),
    ('Medu','Anne eğitimi','ordinal','0–4; artan eğitim düzeyi'),
    ('Fedu','Baba eğitimi','ordinal','0–4; artan eğitim düzeyi'),
    ('Mjob','Anne mesleği','category','teacher, health, services, at_home, other'),
    ('Fjob','Baba mesleği','category','teacher, health, services, at_home, other'),
    ('reason','Okul seçim nedeni','category','home, reputation, course, other'),
    ('guardian','Veli','category','mother, father, other'),
    ('traveltime','Okula ulaşım süresi','ordinal','1: <15 dk; 2: 15–30 dk; 3: 30–60 dk; 4: >60 dk'),
    ('studytime','Haftalık çalışma süresi grubu','ordinal','1: <2 saat; 2: 2–5; 3: 5–10; 4: >10; bunlar saat değerleri değildir'),
    ('failures','Önceki başarısızlık sayısı','numeric','Kaynak dosyadaki başarısızlık sayısı/kodu; özgün sözlüğe bakın'),
    ('schoolsup','Ek okul desteği','category','yes: evet, no: hayır'),
    ('famsup','Aileden eğitim desteği','category','yes: evet, no: hayır'),
    ('paid','Ücretli ek ders','category','yes: evet, no: hayır'),
    ('activities','Ders dışı etkinlik','category','yes: evet, no: hayır'),
    ('nursery','Okul öncesi eğitim','category','yes: evet, no: hayır'),
    ('higher','Yükseköğretim isteği','category','yes: evet, no: hayır'),
    ('internet','Evde internet','category','yes: evet, no: hayır'),
    ('romantic','Romantik ilişki','category','yes: evet, no: hayır'),
    ('famrel','Aile ilişkileri','ordinal','1: çok kötü – 5: mükemmel'),
    ('freetime','Okul sonrası serbest zaman','ordinal','1: çok az – 5: çok fazla'),
    ('goout','Arkadaşlarla dışarı çıkma','ordinal','1: çok az – 5: çok fazla'),
    ('Dalc','Hafta içi alkol tüketimi','ordinal','1: çok az – 5: çok fazla'),
    ('Walc','Hafta sonu alkol tüketimi','ordinal','1: çok az – 5: çok fazla'),
    ('health','Sağlık durumu','ordinal','1: çok kötü – 5: çok iyi'),
    ('absences','Devamsızlık','numeric','Devamsızlık sayısı; kaynak sözlüğündeki sınır 0–93'),
    ('G1','Birinci dönem notu','numeric','0–20 puan'),
    ('G2','İkinci dönem notu','numeric','0–20 puan'),
    ('G3','Dönem sonu notu','numeric','0–20 puan; 0 geçerli bir nottur, eksik değildir'),
]
columns=[dict(key=k,label=l,type=t,note=n) for k,l,t,n in definitions]
numeric={c['key'] for c in columns if c['type'] in ('numeric','ordinal')}
with (ROOT/'veriler/student-mat.csv').open(encoding='utf-8',newline='') as f:
    rows=[{k:float(v) if k in numeric else v for k,v in r.items()} for r in csv.DictReader(f,delimiter=';')]
assert len(rows)==395 and len(rows[0])==33
with (ROOT/'veriler/kitap-b14.csv').open(encoding='utf-8',newline='') as f:
    lab=[{k:v if k=='grup' else float(v) for k,v in r.items()} for r in csv.DictReader(f)]
assert len(lab)==16
for row in lab: row['degisim']=row['son']-row['on']
datasets=[
    dict(id='uci',name='Kitaptaki gerçek veri · UCI / 395 öğrenci',short='UCI Student Performance (matematik)',
         source='Cortez, P. (2008). Student Performance. UCI Machine Learning Repository. İki Portekiz okulu; gözlemsel veri, Türkiye/PDR evrenini temsil etmez. Özgün 395 satır ve 33 değişken korunmuştur. CC BY 4.0.',
         url='https://archive.ics.uci.edu/dataset/320/student+performance',columns=columns,rows=rows),
    dict(id='book',name='Bölüm 14 · Kitabın 16 öğrencilik örneği',short='Kitap, Tablo 14.2 (16 gözlem)',
         source='İbrahim Güney, Temel İstatistik: PDR Araştırmaları İçin Veri Okuryazarlığı, V3 taslak, Bölüm 14, Tablo 14.2, basılı s. 193. Öğretim amacıyla tasarlanmış yapay veri; gerçek araştırma bulgusu değildir. Değişim = son − ön.',
         url='',columns=[dict(key=k,label=l,type=t,note=n) for k,l,t,n in [
             ('id','Öğrenci kodu','id','Anonim örnek kayıt kodu; nicel değişken değildir'),
             ('grup','Öğretim yaklaşımı','category','A ve B; sekizer öğrenci'),
             ('on','Ön-test','numeric','0–100 puan'),('son','Son-test','numeric','0–100 puan'),
             ('saat','Haftalık çalışma','numeric','Saat; veri sözlüğü sınırı 0–40'),
             ('degisim','Son − ön farkı','numeric','Kaynak iki sütundan türetilmiştir')]],rows=lab)
]
(ROOT/'assets/data.js').write_text('// Generated by veriler/hazirla.py; original source and license: veriler/KAYNAKLAR.md\n'+'globalThis.LAB_DATA = '+json.dumps(datasets,ensure_ascii=False,separators=(',',':'))+';\n',encoding='utf-8')
print('2 veri seti, 411 gözlem: assets/data.js üretildi.')
